### ISSUE TITLE
{Req Help} usage

### ISSUE THREAD

**Issue by ElizabethHanson1999** [G00Dway/BlestSploit#1]
Hi 
Thank you for sharing .
I installed BlestSploit . 
Is there any guide how to use it ? 
I couldn't get to btf > command line.
I searched but i didn't find any documentation for that.

**Comment by thez3nith** [comment]
Hello! Thank you for installing BlestSploit!

Instructions:
- Install the framework running the `install-framework.sh` script
- After installing, run `btconsole` in your terminal, and you will see the frameworks console
- To exit from console just type `exit` in frameworks console

And the framework is in Turkish language, so if you want to use it on English version, There are no English version of the framework, but we are working on it right now and we will try to add more languages as we can! Thank you!
