### ISSUE TITLE
english

### ISSUE THREAD

**Issue by sec13b** [G00Dway/BlestSploit#3]
can your change the language in English.

and some commands ,i dont understand 

example , i want test a local ip 192.168.2.237 who have windows server 
Masala

**Comment by thez3nith** [comment]
> can your change the language in English.
> 
> and some commands ,i dont understand
> 
> example , i want test a local ip 192.168.2.237 who have windows server Masala

Hello, You Can Change To Enligh Language In The Setup Screen, The English Language Isn't Supported Fully For Now, But it Will Soon, I am currently working on this!

**Comment by sec13b** [comment]
i test also with , didn't get any result
